### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by acegreen** [huynguyencong/DataCache#1]
When I do:

```
        if let topStoriesCacheData = DataCache.defaultCache.readDataForKey("TOPSTORIESCACHEDATA") {
            self.updateTopStories(topStoriesCacheData)
        }

```

crashes on the if statement, doesn't even go inside

**Comment by acegreen** [comment]
More specifically there doesn't seem to find a FileManager here:

```
    public func readDataFromDiskForKey(key: String) -> NSData? {
        return self.fileManager.contentsAtPath(cachePathForKey(key))
    }
```

<img width="622" alt="screen shot 2016-07-16 at 9 50 38 am" src="https://cloud.githubusercontent.com/assets/10794609/16895174/df68e9d8-4b3a-11e6-89fc-acceb724ad30.png">

**Comment by acegreen** [comment]
2016-07-16 14:14:17.882 StockSwipe[8021:1539265] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSObject contentsAtPath:]: unrecognized selector sent to instance 0x12785ef80'

**Comment by huynguyencong** [comment]
Does it happen again? Have you found the reason?

**Comment by acegreen** [comment]
Happens quit frequenctly on app launch. I need to set filemanager from the get-go

`var fileManager = NSFileManager()`

But even then, it happens once in a blue moon

**Comment by huynguyencong** [comment]
I fixed this bug. Please update to 1.1 version and tell me the result.
Thank you!
