### ISSUE TITLE
Crashes in iOS 11

### ISSUE THREAD

**Issue by nevrborn** [huynguyencong/DataCache#13]
Hello,

since the update to iOS 11 I am getting a lot of crashes involving DataCache. Here is two crash reports:

Thread 5 Crashed:\
0   libswiftCore.dylib                   0x0000000103065e5c 0x102d78000 + 3071580\
1   libswiftCore.dylib                   0x0000000103065e90 0x102d78000 + 3071632\
2   DataCache                            0x0000000102ac697c specialized closure #1 in DataCache.cleanExpiredDiskCacheWithCompletionHander(completionHandler:) (DataCache.swift:0)
3   DataCache                            0x0000000102ac5c4c partial apply for closure #1 in DataCache.cleanExpiredDiskCacheWithCompletionHander(completionHandler:) (DataCache.swift:0)
4   DataCache                            0x0000000102ac117c thunk for @callee_owned () -> () (DataCache.swift:0)
5   libdispatch.dylib                    0x0000000183ced088 _dispatch_call_block_and_release + 20\
6   libdispatch.dylib                    0x0000000183ced048 _dispatch_client_callout + 12\
7   libdispatch.dylib                    0x0000000183cf6e48 _dispatch_queue_serial_drain$VARIANT$mp + 524\
8   libdispatch.dylib                    0x0000000183cf77d8 _dispatch_queue_invoke$VARIANT$mp + 336\
9   libdispatch.dylib                    0x0000000183cf8200 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 396\
10  libdispatch.dylib                    0x0000000183d004a0 _dispatch_workloop_worker_thread$VARIANT$mp + 640\
11  libsystem_pthread.dylib              0x0000000183f92fe0 _pthread_wqthread + 928\
12  libsystem_pthread.dylib              0x0000000183f92c30 start_wqthread + 0\

Thread 3 Crashed:
0   libsystem_platform.dylib             0x00000001809ce8f8 OSAtomicDequeue$VARIANT$mp + 12
1   libsystem_malloc.dylib               0x0000000180908c1c _nano_malloc_check_clear + 148
2   libsystem_malloc.dylib               0x0000000180907ce0 nano_calloc + 76
3   libsystem_malloc.dylib               0x00000001808f94f0 malloc_zone_calloc + 164
4   libsystem_malloc.dylib               0x00000001808f9424 calloc + 36
5   libobjc.A.dylib                      0x00000001802c1238 realizeClass(objc_class*) + 72
6   libobjc.A.dylib                      0x00000001802bee9c _class_getNonMetaClass + 136
7   libobjc.A.dylib                      0x00000001802c5740 lookUpImpOrForward + 220
8   libobjc.A.dylib                      0x00000001802d0758 _objc_msgSend_uncached + 52
9   FileProvider                         0x000000018836f870 FPBookmarkableStringFromDocumentURL + 124
10  CoreServicesInternal                 0x00000001a2661f6c createBookmarkWithURLAtDepth(__CFAllocator const*, __CFURL const*, unsigned long, __CFURL const*, __CFArray const*, BookmarkMutableData&, unsigned int, bool, __CFError**) + 328
11  CoreServicesInternal                 0x00000001a2661ddc _CFURLCreateBookmarkData + 240
12  CoreFoundation                       0x0000000180ddd204 -[NSURL bookmarkDataWithOptions:includingResourceValuesForKeys:relativeToURL:error:] + 240
13  libswiftFoundation.dylib             0x0000000101d5b024 0x101cac000 + 716836
14  DataCache                            0x000000010155e8a0 specialized closure #1 in DataCache.cleanExpiredDiskCacheWithCompletionHander(completionHandler:) (DataCache.swift:302)15  DataCache                            0x000000010155dc4c partial apply for closure #1 in DataCache.cleanExpiredDiskCacheWithCompletionHander(completionHandler:) (DataCache.swift:0)16  DataCache                            0x000000010155917c thunk for @callee_owned () -> () (DataCache.swift:0)17  libdispatch.dylib                    0x000000018072d088 _dispatch_call_block_and_release + 20
18  libdispatch.dylib                    0x000000018072d048 _dispatch_client_callout + 12
19  libdispatch.dylib                    0x0000000180736e48 _dispatch_queue_serial_drain$VARIANT$mp + 524
20  libdispatch.dylib                    0x00000001807377d8 _dispatch_queue_invoke$VARIANT$mp + 336
21  libdispatch.dylib                    0x0000000180738200 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 396
22  libdispatch.dylib                    0x00000001807404a0 _dispatch_workloop_worker_thread$VARIANT$mp + 640
23  libsystem_pthread.dylib              0x00000001809d2fe0 _pthread_wqthread + 928
24  libsystem_pthread.dylib              0x00000001809d2c30 start_wqthread + 0

Any idea what is causing this and how it can be resolved? Let me know if you need more info from me.

**Comment by huynguyencong** [comment]
I've just updated new version, please check it

**Comment by nevrborn** [comment]
After the update I cannot see the crashes again :-) thanks
