### ISSUE TITLE
Notifier of cache expiration.

### ISSUE THREAD

**Issue by alii805** [huynguyencong/DataCache#14]
I have the issue to clean the cache. I am curious if the is completion block for cache expire that automatically called so I should be able to know that it is a time to go for server to fetch the fresh one.

**Comment by huynguyencong** [comment]
It'll auto clean cache when app enter background and disk cache size is bigger than `maxDiskCacheSize`. So if you want to check whether you should fetch from server, just read that resource from cache, if it return nil, it means the resource has been deleted.
