### ISSUE TITLE
Compiler error with swift 4.2

### ISSUE THREAD

**Issue by divyagoel-kiwi** [huynguyencong/DataCache#16]
I installed the data cache via pod (Installing DataCache 1.4). It shows that it downloads 1.4 i.e latest version. I am trying to compiler it but it gives error in datacache.swift file
![screen shot 2018-11-02 at 3 02 00 pm](https://user-images.githubusercontent.com/1144724/47906946-47804880-deb0-11e8-9ed1-bb265682e943.png)

**Comment by huynguyencong** [comment]
Please update your project to Swift version 4.2, or use previous version of DataCache
