### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by neodave** [huynguyencong/DataCache#20]
Hello, I noticed your example of reading images is out of date. Someone change the method readImage to readImageFromKey.

Your docs read 
 let image = DataCache.instance.readImage(forKey: "imageKey")

Should read
let image = DataCache.instance.readImageForKey(key: "imageKey")

Otherwise really enjoying the framework, thanks! 🤠

**Comment by huynguyencong** [comment]
It is my mistake in the source code. It should be `DataCache.instance.readImage(forKey: "imageKey")`. So I will update the code to match the correct version in doc.
Thanks for your notice!
