### ISSUE TITLE
DataCache on macOS?

### ISSUE THREAD

**Issue by amirsaam** [huynguyencong/DataCache#24]
Is it possible to update UIKit part conditionally with AppKit to make this package work on macOS projects too?

**Comment by huynguyencong** [comment]
I will consider it in the future, but not now. If you can, please help to implement it then make a pull request. Thank you!

**Comment by amirsaam** [comment]
Thanks for the response, well I can mark UIKit with this
```swift
#if os(iOS)
    import UIKit
#elseif os(OSX)
    import AppKit
#endif
```
and mark `UIImage` with a `#if os(iOS)`, if that is good enough for you, I'll send a pr right away. it's base functionality, that needs to add image support for macOS later on.
(and edit package availability ofc)

ps: was this issue always there?
```swift
Non-'@objc' instance method in extensions cannot be overridden; use 'public' instead
```
on
```swift
open func cleanExpiredDiskCache(completion handler: (()->())? = nil) {
```
