### ISSUE TITLE
Conform to Swift 3

### ISSUE THREAD

**Issue by acegreen** [huynguyencong/DataCache#3]
Hey, I have changes for Swift 3. Do you want to create a new branch or should I pull to either develop or directly to the master branch?

The changes are 90% compliant except two things related to unSafePointers

**Comment by huynguyencong** [comment]
I created a 'swift3' branch. You can push to there. Thank you for you contribution!

**Comment by huynguyencong** [comment]
I merged it. Before I merge it to master branch, please specify `pod DataCache, :branch => 'swift3'` in your pod file

**Comment by acegreen** [comment]
You shouldn't merge this. Did you read the comments? There are still two errors I couldn't solve.

**Comment by huynguyencong** [comment]
Can you fix it? Because now I'm in Xcode 7.3.1, and need delay update to Xcode 8 a few weeks.

**Comment by acegreen** [comment]
If I could fix it, it would have been done mate. I asked for your input on them. It's regarding UnsafePointers which I'm not familiar with

**Comment by huynguyencong** [comment]
Does you urgent? Could you wait for a few weeks or a few days?

**Comment by acegreen** [comment]
Well my progress is stuck without this library. Xcode won't even show me other errors until I resolve these two.

**Comment by huynguyencong** [comment]
OK, so I'll try fix it as soon as posible

**Comment by acegreen** [comment]
They should be fairly straight forward, I just don't have experience in this area, SK I pushed things as far as I could.

**Comment by acegreen** [comment]
@huynguyencong any update on this?

**Comment by huynguyencong** [comment]
Just update code conform to Swift 3 at "swift3" branch, but haven't updated new version to CocoaPod. If you are urgent, you can specify your pod to "swift3" branch. I will update CocoaPod soon.

**Comment by huynguyencong** [comment]
Updated to Cocoapod. Please run 'pod update'. There are some change in function call

**Comment by acegreen** [comment]
So is the master now swift3 compatible? if so, delete the swift 3 branch to avoid confusion

**Comment by huynguyencong** [comment]
Master was merged from swift3 branch. I will delete swift3 branch now. Completely compatible with swift 3
