### ISSUE TITLE
How to remove from cache

### ISSUE THREAD

**Issue by otymartin** [huynguyencong/DataCache#5]
@huynguyencong 

Is it possible to remove from the cache?

For my usecase, when I remove an object from my server storage, my device is notified at which point i want to remove the file from memory.

**Comment by huynguyencong** [comment]
You can use one of below method. I just updated docs to Readme file
DataCache.instance.clean(byKey: "myKey")
DataCache.instance.cleanAll()

**Comment by otymartin** [comment]
@huynguyencong 
clean method doesn't exist. I can't call it!

**Comment by otymartin** [comment]
@huynguyencong 
You marked it as private. could that be why?

``` swift
fileprivate extension DataCache {

    /// Clean all mem cache and disk cache. This is an async operation.
    public func cleanAll() {
        cleanMemCache()
        cleanDiskCache()
    }
```

**Comment by huynguyencong** [comment]
Oh sorry, it is my mistake when I update for Swift 3. I'll fix it in 1 day

**Comment by otymartin** [comment]
@huynguyencong is there a temporary fix i can do? Im about to submit my app to the appstore. I had set it to public however in building it using `buddybuild.com` there was a warning

`````` swift
▸ Processing Target\ Support\ Files/DataCache/Info.plist
128
    ▸ Compiling DataCache.swift
129
    ⚠ /tmp/sandbox/workspace/Pods/DataCache/Sources/DataCache.swift:[175,5] declaring a public instance method in a fileprivate extension
130
    ✗     public func hasDataOnDiskForKey(key: String) -> Bool {
131
    ✗     ^~~~~~
132
    ⚠ /tmp/sandbox/workspace/Pods/DataCache/Sources/DataCache.swift:[180,5] declaring a public instance method in a fileprivate extension
133
    ✗     public func hasDataOnMemForKey(key: String) -> Bool {
134
    ✗     ^~~~~~
135
    ⚠ /tmp/sandbox/workspace/Pods/DataCache/Sources/DataCache.swift:[303,42] no calls to throwing functions occur within 'try' expression
136
    ✗                     let resourceValues = try URL.resourceValues(forKeys: Set(resourceKeys), fromBookmarkData: bookmarkData)?.allValues
137
    ✗                                          ^```
``````

**Comment by huynguyencong** [comment]
What is your modification. I think you can try to remove "fileprivate" keyword in extension which contain clean method.

```
extension DataCache {
}
```

instead of:

```
fileprivate extension DataCache {
}
```

**Comment by huynguyencong** [comment]
Fixed it. Please run 'pod update' to update DataCache to version 1.2.2.
Thanks!

**Comment by otymartin** [comment]
@huynguyencong thanks just updated

cheers! :)
